version: '2'
services:
  db:
      image: mariadb:latest
      container_name: lemp_mariadb
      restart: always
      volumes:
        - ./mysql/initdb/:/docker-entrypoint-initdb.d
        - ./mysql/data/:/var/lib/mysql
      env_file:
        - ./env/mariadb.env
      ports:
        - 3306:3306
      
  php:
      image: php:7.2-fpm
      container_name: lemp_php-fpm
      restart: always
      links : 
        - db
      volumes:
        - ./www/:/var/www/
      expose:
        - 9000

  node:
      image: node:11
      container_name: lemp_node
      restart: always
      build : ./_react
      volumes:
        - ./_react/:/var/www/_react
      command: ["node", "server.js"]
      expose:
        - 5000


  nginx:
      image: nginx:alpine
      container_name: lemp_nginx
      restart: always
      volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
      volumes_from:
        - php
      ports:
        - 8088:80
      depends_on:
      - php
      - node

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: lemp-phpmyadmin
    restart: always
    env_file:
        - ./env/pma.env
    expose:
      - 80
